### ISSUE TITLE
support for volumes

### ISSUE THREAD

**Issue by chpio** [containers/podman-compose#13]
* shared volumes (defined in the root section of the docker-compose file)
  * and support for mounting these volumes in services
* "just" volumes, a path to mount a value at that place (is this even needed with 1. in place?)

<https://docs.docker.com/compose/compose-file/#volumes>

**Comment by muayyad-alsadi** [comment]
"just" volumes is already supported, but shared volumes needs some work. I'll see what I can do.

**Comment by chpio** [comment]
> "just" volumes is already supported

im getting an error for 

```yaml
services:
  web:
    # ...
    volumes:
      - "/var/www/storage"
```

> Error: incorrect volume format "/var/www/storage", should be host-dir:ctr-dir[:option]

**Comment by muayyad-alsadi** [comment]
understood, so the podman commands would be

```
$ podman volume create myvol
$ v=`podman volume inspect myvol | jq -r '.[0].mountPoint'`
$ podman run -v $v:/var/www/storage  ...
```

**Comment by muayyad-alsadi** [comment]
the long syntax has 3 types: `volume`, `bind` or `tmpfs`

```
- type: volume
  source: mydata # this is a name
  target: /data
  read_only: false
  # type-specific options
  tmpfs: {size: 123, mode: 1777}
  volume: {nocopy: true} 
  bind: {propagation: Z, z, shared, slave, private, rshared, rslave, or rprivate(default)}
```

there are more than one shorthand syntax for compose

```
  # Just specify a path and let the Engine create a volume
  - /var/lib/mysql

  # Specify an absolute path mapping
  - /opt/data:/var/lib/mysql

  # Path on the host, relative to the Compose file
  - ./cache:/tmp/cache

  # User-relative path
  - ~/configs:/etc/configs/:ro

  # Named volume
  - datavolume:/var/lib/mysql
```

those can be passed to podman using: (which is what currently used)

- `--tmpfs /tmp:rw,size=787448k,mode=1777`
- `-v HOST-DIR:CONTAINER-DIR:OPTIONS`

where options can be

- [rw|ro]
- [z|Z]
- [[r]shared|[r]slave|[r]private]

or unified `--mount` like this

- `--mount type=tmpfs,tmpfs-size=512M,destination=/path/in/container`
- `--mount type=bind,source=/path/on/host,destination=/path/in/container`

**Comment by muayyad-alsadi** [comment]
@chpio  please test, this is now fully implemented 

https://github.com/muayyad-alsadi/podman-compose/commit/5606c69f9d3acf8ba091ac2937c933dbd3bcb584

and 

https://github.com/muayyad-alsadi/podman-compose/commit/fc61e0168b6636440c7f90d336de776be7953645

**Comment by chpio** [comment]
thank you!

those commits seem to have broken something:

on commit fc61e0168b6636440c7f90d336de776be795364 (882cef73b7f354b6c2f5cfce88035bbf7ec7ca65 seem to work fine)

```
$ podman-compose up
podman stop -t=1 vmz-nds-base_web_1
Error: no container with name or ID vmz-nds-base_web_1 found: no such container
125
podman rm vmz-nds-base_web_1
Error: no container with name or ID vmz-nds-base_web_1 found: no such container
1
podman pod rm vmz-nds-base
Error: no pod with name or ID vmz-nds-base found: no such pod
125
podman pod create --name=vmz-nds-base --share net -p 8080:80
c5c2a81eac58619f51540ea97394cee227d648c94664c1c3b87809a82e5ce5cf
0
Traceback (most recent call last):
  File "/home/thomas/bin/podman-compose", line 710, in <module>
    main()
  File "/home/thomas/bin/podman-compose", line 705, in main
    podman_path=args.podman_path
  File "/home/thomas/bin/podman-compose", line 665, in run_compose
    no_cleanup, dry_run, podman_path, shared_vols)
  File "/home/thomas/bin/podman-compose", line 555, in up
    args = container_to_args(cnt, dirname, podman_path, shared_vols)
  File "/home/thomas/bin/podman-compose", line 434, in container_to_args
    i, podman_path, cnt['_dirname'],
KeyError: '_dirname'

```

My dockerfile:
```yaml
version: '3'
services:
  web:
    build: containers/web
    ports:
      - "8080:80"
    volumes:
      - ./dist:/var/www/html
```

**Comment by chpio** [comment]
thank you!

those commits seem to have broken something:

on commit fc61e0168b6636440c7f90d336de776be795364 (882cef73b7f354b6c2f5cfce88035bbf7ec7ca65 seem to work fine)

```
$ podman-compose up
podman stop -t=1 foo_web_1
Error: no container with name or ID foo_web_1 found: no such container
125
podman rm foo_web_1
Error: no container with name or ID foo_web_1 found: no such container
1
podman pod rm foo
Error: no pod with name or ID foo found: no such pod
125
podman pod create --name=foo --share net -p 8080:80
c5c2a81eac58619f51540ea97394cee227d648c94664c1c3b87809a82e5ce5cf
0
Traceback (most recent call last):
  File "/home/thomas/bin/podman-compose", line 710, in <module>
    main()
  File "/home/thomas/bin/podman-compose", line 705, in main
    podman_path=args.podman_path
  File "/home/thomas/bin/podman-compose", line 665, in run_compose
    no_cleanup, dry_run, podman_path, shared_vols)
  File "/home/thomas/bin/podman-compose", line 555, in up
    args = container_to_args(cnt, dirname, podman_path, shared_vols)
  File "/home/thomas/bin/podman-compose", line 434, in container_to_args
    i, podman_path, cnt['_dirname'],
KeyError: '_dirname'

```

My dockerfile:
```yaml
version: '3'
services:
  web:
    build: containers/web
    ports:
      - "8080:80"
    volumes:
      - ./dist:/var/www/html
```

**Comment by muayyad-alsadi** [comment]
I've just pushed a29cf06436c41358c000ab2316974397dcc699fc

please test

**Comment by chpio** [comment]
im getting this now

```
Traceback (most recent call last):
  File "/home/thomas/bin/podman-compose", line 740, in <module>
    main()
  File "/home/thomas/bin/podman-compose", line 735, in main
    podman_path=args.podman_path
  File "/home/thomas/bin/podman-compose", line 693, in run_compose
    no_cleanup, dry_run, podman_path, shared_vols)
  File "/home/thomas/bin/podman-compose", line 570, in up
    args = container_to_args(cnt, dirname, podman_path, shared_vols)
  File "/home/thomas/bin/podman-compose", line 436, in container_to_args
    shared_vols
  File "/home/thomas/bin/podman-compose", line 362, in mount_desc_to_args
    if is_str(mount_desc): mount_desc=parse_short_mount(mount_desc, basedir)
  File "/home/thomas/bin/podman-compose", line 78, in parse_short_mount
    for opt in mount_opt.split(','):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by muayyad-alsadi** [comment]
I've handled the case

**Comment by chpio** [comment]
```
Traceback (most recent call last):
  File "/home/thomas/bin/podman-compose", line 741, in <module>
    main()
  File "/home/thomas/bin/podman-compose", line 736, in main
    podman_path=args.podman_path
  File "/home/thomas/bin/podman-compose", line 694, in run_compose
    no_cleanup, dry_run, podman_path, shared_vols)
  File "/home/thomas/bin/podman-compose", line 571, in up
    args = container_to_args(cnt, dirname, podman_path, shared_vols)
  File "/home/thomas/bin/podman-compose", line 437, in container_to_args
    shared_vols
  File "/home/thomas/bin/podman-compose", line 365, in mount_desc_to_args
    mount_type = mount_desc.get("type")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by muayyad-alsadi** [comment]
I've sorry for bothering you with me. I've pushed a fix. I'll create a compose file and test all the cases ASAP

**Comment by muayyad-alsadi** [comment]
I've fixed all of issues and added tests

as you can see [here](https://github.com/muayyad-alsadi/podman-compose/blob/master/test/short/docker-compose.yaml) and [here](https://github.com/muayyad-alsadi/podman-compose/blob/master/test/vol/docker-compose.yaml)

**Comment by chpio** [comment]
thx, that dockerfile from above is working now, but i haven't tested volumes as a whole ("external" volumes syntax).

**Comment by muayyad-alsadi** [comment]
thank you.

I'll keep this ticket open until I test all cases.

**Comment by xcffl** [comment]
Volumes currently works. But the way podman-compose claims volumes might require some polish.
It allocates the volume and uses --mount to mount that path. But if we then execute `podman prune`, those volumes are considered as orphans and will be **removed**.

**Comment by muayyad-alsadi** [comment]
how do you suggesting passing them to `podman run`?

**Comment by xcffl** [comment]
> how do you suggesting passing them to `podman run`?
````
podman run -m data:/app/data
````
Although it's undocumented, it works the same way as [Docker's named volumes](https://docs.docker.com/storage/volumes/).

**Comment by muayyad-alsadi** [comment]
starting from which podman version they have this option?

**Comment by muayyad-alsadi** [comment]
I've podman 1.2.0 and it shows
```
$ podman run --help
...
  -m, --memory string                            Memory limit (format: <number>[<unit>], where unit = b, k, m or g)
...
```

**Comment by xcffl** [comment]
> I've podman 1.2.0 and it shows
> 
> ```
> $ podman run --help
> ...
>   -m, --memory string                            Memory limit (format: <number>[<unit>], where unit = b, k, m or g)
> ...
> ```

Sorry, my mistake. They don't have `-m`, but they have `-v`, `--mount`, and `--volume`.
`sudo podman run --rm -v test-data:/data ubuntu` is definitely valid.
````
➜  ~ sudo podman run --rm -v test-data:/data ubuntu   
➜  ~ sudo podman volume ls
DRIVER   VOLUME NAME
local    test-data
````

**Comment by muayyad-alsadi** [comment]
I've reviewed the code and found that I'm already using `--mount` and we can easily pass it as-is if supported by podman. we just need to know when `podman run --mount volume:source:/path/to/target` is supported

```
       type=volume,source=my-volume,destination=/path/in/container,volume-label="color=red",volume-label="shape=round"
```

**Comment by xcffl** [comment]
> I've reviewed the code and found that I'm already using `--mount` and we can easily pass it as-is if supported by podman. we just need to know when `podman run --mount type=volume:source=vol-name:destination=/path/to/target` is supported
> 
> ```
>        type=volume,source=my-volume,destination=/path/in/container,volume-label="color=red",volume-label="shape=round"
> ```

I don't know when exactly it is supported. And according to the discussion in https://github.com/containers/libpod/issues/3811 they fogot to add documentation when they add that functionality.

 I just know that podman 1.4.4 supports it.

**Comment by muayyad-alsadi** [comment]
we need to know how to pass `:z` for volume types.

https://github.com/containers/podman-compose/issues/41#issuecomment-531421705

**Comment by mpnordland** [comment]
Since this issue seems to be tracking volumes support, I'll add this here.
At this line: https://github.com/containers/podman-compose/blob/b369073574f18a775cd91be856920d14cf43f873/podman_compose.py#L381
In podman v1.6.0 the key is spelled "Mountpoint". This causes the following stacktrace:
```
Traceback (most recent call last):
  File "/home/micah/dev/boilerplate/venv/bin/podman-compose", line 10, in <module>
    sys.exit(main())
  File "/home/micah/dev/boilerplate/venv/lib/python3.7/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/home/micah/dev/boilerplate/venv/lib/python3.7/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/home/micah/dev/boilerplate/venv/lib/python3.7/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/home/micah/dev/boilerplate/venv/lib/python3.7/site-packages/podman_compose.py", line 898, in compose_up
    detached=args.detach, podman_command=podman_command)
  File "/home/micah/dev/boilerplate/venv/lib/python3.7/site-packages/podman_compose.py", line 457, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/home/micah/dev/boilerplate/venv/lib/python3.7/site-packages/podman_compose.py", line 386, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/home/micah/dev/boilerplate/venv/lib/python3.7/site-packages/podman_compose.py", line 366, in mount_dict_vol_to_bind
    src = json.loads(out)[0]["mountPoint"]
KeyError: 'mountPoint'
```

**Comment by dinokov** [comment]
I have the same problem.
Every time I put top-level volumes key in docker-compose.yml file I get the same error after running :
```
podman-compose up

...
podman volume inspect webdevops-1604_mysql || podman volume create webdevops-1604_mysql
Traceback (most recent call last):
  File "/home/damir/.local/bin/podman-compose", line 10, in <module>
    sys.exit(main())
  File "/home/damir/.local/lib/python3.7/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/home/damir/.local/lib/python3.7/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/home/damir/.local/lib/python3.7/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/home/damir/.local/lib/python3.7/site-packages/podman_compose.py", line 898, in compose_up
    detached=args.detach, podman_command=podman_command)
  File "/home/damir/.local/lib/python3.7/site-packages/podman_compose.py", line 457, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/home/damir/.local/lib/python3.7/site-packages/podman_compose.py", line 386, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/home/damir/.local/lib/python3.7/site-packages/podman_compose.py", line 366, in mount_dict_vol_to_bind
    src = json.loads(out)[0]["mountPoint"]
KeyError: 'mountPoint'

```
If I comment out last lines like this:
```
     #volumes:
       #phpmyadmin:
       #db_data: 
```
then the error is no more !
I am using podman version 1.6.1

**Comment by muayyad-alsadi** [comment]
but this is already handled here

https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L384

```python
    try:
        src = json.loads(out)[0]["mountPoint"]
    except KeyError:
        src = json.loads(out)[0]["Mountpoint"]
```

please use devel branch as in README.

**Comment by dinokov** [comment]
I installed devel branch and can use volumes now .

Thank you very much !

**Comment by herochao** [comment]
Hey, not sure if this is still current, but it seems fitting for my issue: 
System: CentOS8 using python 3.6 with podman 1.0.5 

On inspection of volumes, the command `podman volume inspect {volname}` seems to return 
```python 
"null\n"
``` 
along with the returncode 0. 

As a result, in **line 381**, no `subprocess.CalledProcessError` is raised and podman-compose doesn't try to create it.
It works as intended using the following modification:
```python
    try:
        out = compose.podman.output(["volume", "inspect", vol_name]).decode('utf-8')
        if out == "null\n":
            raise subprocess.CalledProcessError(0, "podman volume inspect "+vol_name)
    except subprocess.CalledProcessError:
```
I did not create a pull-request since it is a small change and kind of a hacky solution :/

**Comment by mheon** [comment]
That sounds suspiciously like a Podman bug. Does the volume in question
exist when inspect returns that?

**Comment by xtrasimplicity** [comment]
> but this is already handled here
> 
> https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L384
> 
> ```python
>     try:
>         src = json.loads(out)[0]["mountPoint"]
>     except KeyError:
>         src = json.loads(out)[0]["Mountpoint"]
> ```
> 
> please use devel branch as in README.

Is there a new pip-release scheduled? It was quite surprising to install the latest version via pip expecting a functional, drop-in docker-compose replacement, but to then immediately run into this issue when running `podman-compose up`.

**Comment by leonardehrenfried** [comment]
I too would love to see this released!

Andrew <notifications@github.com> schrieb am Di., 5. Nov. 2019, 09:29:

**Comment by muayyad-alsadi** [comment]
Fixing Mounts and up then release

**Comment by herochao** [comment]
The problem is that `out = "null\n"` in my situation (since podman doesn't error but doesn't return anything either), and so the json parsing always fails :/ 
I was using the devel branch for that.

**Comment by jaorueta** [comment]
In the function `mount_desc_to_args`:

```
if mount_type=='bind':
elif mount_type=='tmpfs':
else:
raise ValueError("unknown mount type:"+mount_type)
```

If I understand ok, it not possible to declare `type:volume` in the composer file. I say this because only `volume` pre-populate the volume.

**Comment by muayyad-alsadi** [comment]
We support volume,
We inspect volume get its dir and convert it to bind.

I'm going to change this

**Comment by jaorueta** [comment]
Maybe add some like: 

```
    elif mount_type=='volume':
        return "type=volume,source={source},destination={target},{opts}".format(
            source=source,
            target=target,
            opts=opts
).rstrip(",")
```

**Comment by WheresAlice** [comment]
I have been struggling to get this working today.  The following simply didn't work at all, with no errors:

```
volumes:
    - ./data:/data/
```

After much trial and error, I finally discovered that I need to set the full path, and use the long-form method for defining volumes:

```
    volumes:
     - type: bind
       source: /home/alice/ct/data
       target: /data
```

**Comment by kiview** [comment]
@WheresAlice 
But this kind of breaks the purpose of having a relative path in the local directory in the first place.

@muayyad-alsadi 
Does this mean relative paths in short are not supported atm? Should I raise a seperate issue for this?

**Comment by jerdna-regeiz** [comment]
> @WheresAlice
> But this kind of breaks the purpose of having a relative path in the local directory in the first place.
If it helps, it helps ;) 
But it does not solve further problems (like pre-population). 

> @muayyad-alsadi
> Does this mean relative paths in short are not supported atm? Should I raise a seperate issue for this?
Relative paths are supported, but are converted into absolute paths. The issue is more to Use the real volume mechanism instead of bind. 

I'll share a pull request lauter today, which fixes the issues at least for me.

**Comment by n1trux** [comment]
For some reason:

```
services:
  php:
    image: sqstorage:master
    build: .
    volumes:
      - "app:/app"
      - "./dba.php:/app/support/dba.php:ro"
```

maps to

`[…] --mount type=bind,source=/sqstorage/./dba.php,destination=/app/support/dba.php,ro sqstorage:master […]`

which leads to:

`Error: error checking path "/srv/pod/sqstorage/./dba.php": stat /srv/pod/sqstorage/./dba.php: no such file or directory`

Will that be fixed by #117?

**Comment by salotz** [comment]
I had to change the 'mountPoint' to 'Mountpoint' when using a config like this:

```
volumes:
    grafana_data: {}
services:
  grafana:

    volumes:
      - ./volumes/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana

```

**Comment by allquixotic** [comment]
Hello! It has been quite some months and the `KeyError: 'mountPoint'` issue still persists with the package in PyPi. Is a release forthcoming? Thanks!

**Comment by djnotes** [comment]
I am bind mounting. It seems the bind is successful, but new changes I apply to code do not get reflected in the running app. Here's my docker-compose.yml:    

```
version: '3.0'


services:
    web:
        build: .
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html,Z
```
Dockerfile:   

```
FROM php:7.4-apache

RUN apt-get update \
    &&  apt-get install -y nano \
    && docker-php-ext-install pdo \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY . /var/www/html

WORKDIR /var/www/html

CMD ["apachectl","-DFOREGROUND"]
```

**Comment by x80486** [comment]
I'm using `podman-compose-0.1.5`, `podman-2.0.6`, and `buildah-1.16.0`. I have this simple `docker-compose.yml` file:

```yml
version: "3.8"

services:
  database:
    container_name: postgres-database
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-NgdnckG0z9Er7ASg}
      - POSTGRES_USER=${DB_USER:-postgres}
    healthcheck:
      interval: 10s
      retries: 3
      test: ["CMD", "pg_isready", "--username", "postgres"]
      timeout: 30s
    image: docker.io/library/postgres:12.4-alpine     # https://hub.docker.com/_/postgres/
    networks:
      - global-network
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"

networks:
  global-network:
    driver: bridge
    name: kong-network
```

...and I'm always getting some similar error message(s):

```shell
[x80486@uplink:~/Workshop/Development/kong-api-gateway]$ podman-compose up --build --detach 
podman pod create --name=kong-api-gateway --share net -p 5432:5432
a379479ebd8f6f596a0e62248c4480a7481c6295600f1a03d9909f92a034d285
0
podman volume inspect kong-api-gateway_postgres-data || podman volume create kong-api-gateway_postgres-data
Error: error inspecting volume kong-api-gateway_postgres-data: no volume with name "kong-api-gateway_postgres-data" found: no such volume
Traceback (most recent call last):
  File "/nix/store/591n4x5vk8j55gzi8lrx5gjx7x3lh9n9-podman-compose-0.1.5/bin/.podman-compose-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/591n4x5vk8j55gzi8lrx5gjx7x3lh9n9-podman-compose-0.1.5/lib/python3.8/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/nix/store/591n4x5vk8j55gzi8lrx5gjx7x3lh9n9-podman-compose-0.1.5/lib/python3.8/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/nix/store/591n4x5vk8j55gzi8lrx5gjx7x3lh9n9-podman-compose-0.1.5/lib/python3.8/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/nix/store/591n4x5vk8j55gzi8lrx5gjx7x3lh9n9-podman-compose-0.1.5/lib/python3.8/site-packages/podman_compose.py", line 897, in compose_up
    podman_args = container_to_args(compose, cnt,
  File "/nix/store/591n4x5vk8j55gzi8lrx5gjx7x3lh9n9-podman-compose-0.1.5/lib/python3.8/site-packages/podman_compose.py", line 457, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/nix/store/591n4x5vk8j55gzi8lrx5gjx7x3lh9n9-podman-compose-0.1.5/lib/python3.8/site-packages/podman_compose.py", line 386, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/nix/store/591n4x5vk8j55gzi8lrx5gjx7x3lh9n9-podman-compose-0.1.5/lib/python3.8/site-packages/podman_compose.py", line 366, in mount_dict_vol_to_bind
    src = json.loads(out)[0]["mountPoint"]
KeyError: 'mountPoint'
```

Is there a workaround for this?

**Comment by muayyad-alsadi** [comment]
yes, please don't use 0.1.5, use the latest devel branch instead

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by x80486** [comment]
Not trying to be pushy or anything like that, but wouldn't be better to make a release with all the changes you folks have made since `0.1.5`? I think there is a lot of work already and releasing more frequently will give you more chances to make `podman-compose` better because more users are going to use/test it :partying_face:

**Comment by tinywrkb** [comment]
For my needs, the new volumes support working great. I tested named volumes, bind mounts (short syntax) with relative and absolute paths.  
I suspect like myself, other users might find podman-compose barely usable without volumes support, so it would be nice to see a new release being tagged off master.

**Comment by Marek77** [comment]
Hello, we have the same issue ("mountPoint" vs "Mountpoint") with pip3-installed podman-compose (not devel). Can we please get this fix merged and released ?

**Comment by thegarlynch** [comment]
Still no release ?

**Comment by Jasstkn** [comment]
> There is not much point in using podman-compose anymore, while Podman supports Docker-Compose. You can use Docker Compose with Podman backend now.

I've tried to make it work on Mac but with no lack. :(

**Comment by ChristophP** [comment]
> I've tried to make it work on Mac but with no lack. :(

Same here. Does anyone know if there is a way to expose the podman backend from inside the VM to the host MacOS system?

**Comment by stellarpower** [comment]
> There is not much point in using podman-compose anymore, while Podman supports Docker-Compose. You can use Docker Compose with Podman backend now.

I didn't know we had full support. Ideally I should just move to K8s yaml as my last foray into Ansible wasn't a lot neater. 

I am experienceing a bit of trouble with a sort-of hack I used in docker to get bind-mounted named volumes:

```
version: 3.3
services:
  foo:
    image: ..
    volumes: foo_Config:/config
volumes:
    foo_Config:
      driver: local
      driver_opts:
        device:    $VolumeRoot/foo/Config
        o:         bind
        type:      none
```

Not sure if it belongs here, or a separate issue (or if it could be in Podman itself - would need to work out the correct equivalent chain of CLI commands first). It took quite some time to find out how to do this in Docker, as everything was either named volume or bind-mount, not both as I wanted, to share between containers but back with ZFS.

Is this still worth following up on reporting this, or is development on podman-compose likely to draw to a close if docker-compose can be used instead? Struggling to find much time for GH outside of work these days, but I have a couple more things I've found in podman-compose, and I try to report a least, otherwise nothing can ever be fixed.

**Comment by muayyad-alsadi** [comment]
I'll close this, because latest version of podman-compose solved it.
please if you have an issue reported separately with full details.

we have an issue reported for macos, I don't have a mac, I'm using fedora. so I can't help with that.

**Comment by Zerwin** [comment]
Are there any plans to support the :U volume option ? 

See the documentation here (under "Chowning Volume Mounts"):
https://docs.podman.io/en/latest/markdown/podman-run.1.html

Or here under the 2nd solution:
https://www.redhat.com/sysadmin/debug-rootless-podman-mounted-volumes

Currently using the :U option just throws an error.
```Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1817, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1092, in run
    cmd(self, args)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1311, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1478, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 720, in container_to_args
    podman_args.extend(get_mount_args(compose, cnt, volume))
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 525, in get_mount_args
    if is_str(volume): volume = parse_short_mount(volume, basedir)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 129, in parse_short_mount
    raise ValueError("unknown mount option "+opt)
ValueError: unknown mount option U

**Comment by burredis** [comment]
Hello everybody

I'm using macOS and this issue happened to me.

```
using podman version: 3.4.4
podman-composer version  1.0.3
podman --version 
podman version 3.4.4
```

Does someone have the solution?

Regards,

**Comment by muayyad-alsadi** [comment]
I was told that there is a bug in on MacOS when passing `./somthing/otherthing` that does not happen when using `somthing/otherthing`

I don't have mac.

**Comment by alex198710** [comment]
Hello @burredis,
I have the exact same problem and the same podman versions.
Did you find any solution?
Thanks in advance,
Regards,

**Comment by burredis** [comment]
Hey @alex198710 [alex198710](https://github.com/alex198710),
The solution that I found is to use [colima](https://github.com/abiosoft/colima). It works all that I need.
Can I start docker and all commands and features.

Regards

**Comment by alex198710** [comment]
Thanks @burredis,
I also found https://rancherdesktop.io/
I will check both.
Regards

**Comment by toanvo288** [comment]
Hi there, I using MacOS version Monterey. The volumes tag in compose file does not work at all. 
Noted: I have used PostgreSQL image from docker.io
```
volumes:
      - ./tests/Sql/InitialDbVersion.sql:/docker-entrypoint-initdb.d/InitialDbReleaseVersion.sql
```
      
```
Error: statfs /tests/Sql/InitialDbReleaseVersion.sql: no such file or directory
exit code: 125   
```

**Comment by muayyad-alsadi** [comment]
please try podman v4 on mac
there are reports regarding volumes on mac and v4 solved it.

**Comment by matheussouza9** [comment]
@toanvo288 I'm stuck on the same problem. I found [this article](https://dalethestirling.github.io/Macos-volumes-with-Podman/) that mounts a host dir to the qemu vm using ssh reverse proxy combined with `sshfs`, but, in the last step, I'm getting the following error:
```sh
[core@localhost ~]$ sshfs -p 10000 matheus@127.0.0.1:/Users /mnt/Users
connect_to 127.0.0.1 port 22: failed.
read: Connection reset by peer
```

**Comment by matheussouza9** [comment]
@muayyad-alsadi unfortunately Podman v4 is not available on brew yet. https://github.com/Homebrew/homebrew-core/pull/95318#issuecomment-1043354398

**Comment by viinhpham** [comment]
> Hi there, I using MacOS version Monterey. The volumes tag in compose file does not work at all. Noted: I have used PostgreSQL image from docker.io using podman version: 3.4.4 podman-composer version 1.0.3
> 
> ```
> volumes:
>       - ./tests/Sql/InitialDbReleaseVersion.sql:/docker-entrypoint-initdb.d/InitialDbReleaseVersion.sql
> ```
> 
>  ```
> Error: statfs /tests/Sql/InitialDbReleaseVersion.sql: no such file or directory
> exit code: 125   
> ```

@toanvo288 
- You will need to mount your Mac folder in to podman machine folder  by logging in podman machine and run the ssh reverse proxy command:

sshfs your-username@your-current-local-ip:absolute-path-to-your-local-project-folder your-podman-mounted-forder -o allow_other,uid=1000,gid=1000`

**Comment by toanvo288** [comment]
@viinhpham and @matheussouza9 : thanks all. I'll check and verify it again. Hope it works with Podman version 4 without a workaround.

**Comment by lmsurpre** [comment]
> Hope it works with Podman version 4 without a workaround.

it doesn't

**Comment by drgsn** [comment]
not sure if this happens for windows too, but for mac podman machine starts in a detached state, so it won't be able to access anything from your storage. You need to attach the $HOME to it in order to be able to access volumes

`  podman machine stop podman-machine-default
  podman machine rm podman-machine-default
  podman machine init -v $HOME:$HOME
  podman machine start
`

code stolen from https://stackoverflow.com/questions/69298356/how-to-mount-a-volume-from-a-local-machine-on-podman
