### ISSUE TITLE
option "--no-deps" is ignored for "podman-compose up"

### ISSUE THREAD

**Issue by bam80** [containers/podman-compose#398]
The option has no effect:
```
$ podman-compose up --help
...
  --no-deps             Don't start linked services.

**Comment by muayyad-alsadi** [comment]
to be fair, `--no-deps` only makes sense with run not with up.

but I'll look into it.

**Comment by muayyad-alsadi** [comment]
I've noticed that, I believe `run` with no dependency was understood as up with no argument which mean all.
I'll fix that.

**Comment by muayyad-alsadi** [comment]
@diodakus I've fixed your issue please test.

**Comment by diodakus** [comment]
@muayyad-alsadi I confirm that issue **were solved**.

**Comment by Steiniche** [comment]
@muayyad-alsadi I believe this issue can be closed as resolved.

**Comment by saurabhaahujaa** [comment]
I am still facing issue in below version, podman-compose unnecessary tends to recreate all dependencies when it already exists and --no-deps is given

podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.4.1
podman-compose version 1.0.6
podman --version 
podman version 4.4.1
exit code: 0

**Comment by bailsman** [comment]
I am also experiencing this issue. From the help message, I expected --no-deps to start only the container specified and not start any of the dependencies. However, it also starts the dependencies.

podman-compose version 1.3.0
podman version 5.3.1

Command used:

podman-compose up -d nginx --no-deps --no-recreate
